on:
  push:
    branches:
      - main

name: Build and Deploy
jobs:
  build:
    runs-on: lab-stack-interpreter
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: docker-compose build

      - name: Run
        run: docker-compose down && docker-compose up -d